config/routes.rb
Rails.application.routes.draw do
  

  get 'users/profile_page'

  namespace :api do
    namespace :v1 do
      get 'home', to: 'posts#home'
      post 'users/sign_in', to: 'users#sign_in'
    end
    namespace :v2 do
      get 'home', to: 'posts#home'
      post 'users/sign_in', to: 'users#sign_in'
    end
  end

  post 'likes/toggle/:post_id', to: 'likes#toggle', as: :toggle_like

  post 'comments/create', as: :comments
  delete 'comments/:id', to: 'comments#destroy', as: :destroy_comment

	# Post routes
  root 'posts#home'
  post 'posts/create', as: :posts
  delete 'posts/:id', to: 'posts#destroy', as: :destroy_post

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'posts/home', to: 'posts#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'users/profile/:id', to: 'users#profile_page'
  post 'users/upload_avatar/:id', to: 'users#upload_avatar', as: :user_avatar_upload

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy


	# returns true if a user can like this post
	def user_can_like(user_id)
		if self.likes.where(user_id: user_id).length > 0
			return false
		end

		return true

	end


	def like_status_string(user_id)
		if self.user_can_like(user_id)
			return '<i class="fa fa-thumbs-up"></i>'.html_safe
		else
			return '<i class="fa fa-thumbs-down"></i>'.html_safe

		end

	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable,omniauth_providers: [:google_oauth2]


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.from_omniauth(data)

  	user=User.find_by(email: data.email)
    if user.blank?
    user=User.create(
    	email: data.email,
    	password: SecureRandom.uuid 
    	)
    end

    return user
    
  end


  def set_auth_token
    self.auth_token = SecureRandom.uuid
    self.save
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
	module V1
		class PostsController < ApplicationController
			def home
				@posts=Post.all
				return render json:@posts
			end
		end
	end
end

app/controllers/api/v1/users_controller.rb
module Api
	module V1
		class UsersController < ApplicationController
			def sign_in
				user=User.find_by(email: params[:emial])
				if !user.blank?
					if user.valid_password?(params[:password])
						user.set_auth_token
						return render json: user
					end
				end
				data={
					message: "invalid username or password",
				}

				return render json: data, status: 401
			end
		end
	end

end

app/controllers/api/v2/posts_controller.rb
module Api
	module V2
		class PostsController < ApplicationController
			def home
				@posts=Post.all
				return render json:@posts,each_serializer: PostDetailSerializer
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user, only: [:destroy]


  def create
  	@new_comment = Comment.create(
  		content: params[:comment][:content], 
  		user_id: current_user.id, 
  		post_id: params[:comment][:post_id]
  		)
     UserMailer.new_comment(@new_comment.id).deliver_now

  	# redirect_to root_path

  end

  def destroy
  	@comment.destroy

  	redirect_to root_path
  end

  private

  def set_comment
  	@comment = Comment.find(params[:id])
  end

  def authorize_user
  	if (@comment.user_id != current_user.id)
  		redirect_to root_path
  	end

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!


  def toggle

  	# @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])


  	# if @like.blank?
  	# 	@like = Like.create(user_id: current_user.id, post_id: params[:post_id])

  	# else

  	# 	@like.destroy
  	# end
    @post = Post.find(params[:post_id])

    if @post.user_can_like(current_user.id)

      @like = Like.create(user_id: current_user.id, post_id: params[:post_id])

    else
      Like.find_by(user_id: current_user.id, post_id: params[:post_id]).destroy
    end


  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_post, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def home
    # for new posts
  	@post = Post.new

    # for list of posts
  	@posts = Post.all

    # for new comment
    @comment = Comment.new
    respond_to do|format|
    format.html
    format.json{
      if(params[:detail]=="true")
         return render json:@posts,each_serializer: PostDetailSerializer
      else
        return render json:@posts
      end
    }
  end
  end

  def create

  	@post = Post.create(content: params[:post][:content], user_id: current_user.id)
  	@comment =Comment.new
    # commented for using js request as well
    # redirect_to action: "home"

  end

  def destroy
    @post_id = @post.id
	@post.destroy

  	# redirect_to action: "home"
  end


  private

  def set_post
  	@post = Post.find(params[:id])
  end

  def authorize_user
  	if (@post.user_id != current_user.id)
  		redirect_to action: "home"
  	end

  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      # @user = User.from_omniauth(request.env['omniauth.auth'])
      @user=User.from_omniauth(request.env['omniauth.auth'].info)

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile_page

  	@user = User.find(params[:id])
  	
  end

  def upload_avatar

  	@user = User.find(params[:id])
  	@user.avatar = params[:user][:avatar]
  	@user.save
  	redirect_to request.referrer

  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
	<p><%= comment.content %>
		<sub><%= comment.user.email %></sub>
	</p>
	<% if user_signed_in? && comment.user_id ==  current_user.id %>
		<p><%= link_to "Delete", destroy_comment_path(comment.id), method: :delete %></p>
		<% end %>

</li>

app/views/comments/_post_comment.html.erb
<div>
	<h5>Add Comment</h5>
	<% if user_signed_in? %>
	<%= form_for @comment, remote: true do |f| %>
		<%= f.hidden_field :post_id, value: post.id %>

		<%= f.label :content %>
		<%= f.text_area :content %>

		<%= f.submit %>
	<% end %>
	<% end %>

	<ul id="post-comment-list-<%= post.id %>">
		<% post.comments.reverse.each do |c| %>
		<%= render 'comments/comment', comment: c %>
		<% end %>
	</ul>


</div>

app/views/comments/create.js.erb
console.log('creating comment for a post');

var commentsListContainer = $('#post-comment-list-<%= @new_comment.post_id %>')

var newCommentHTML = $("<%= escape_javascript render 'comments/comment', comment: @new_comment %>");

commentsListContainer.prepend(newCommentHTML);

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connecti</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.css">


  </head>

  <body>
  	<div id="common-header">
  		<div class='logo'>
  			<img width="45" src="https://image.freepik.com/free-icon/reddit-logo_318-67806.jpg">
  		</div>

  		<div class='auth-info-links'>
  			<% if user_signed_in? %>
  			<p><%= current_user.email %></p>
  			<p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>

  			<% else %>

  				<p><%= link_to "Sign In", new_user_session_path %></p>
  				<p><%= link_to "Sign Up", new_user_registration_path %></p>
  			<% end %>
  		</div>
  	</div>


    <%= yield %>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js"></script>
  </body>
</html>

app/views/likes/toggle.html.erb
<h1>Likes#toggle</h1>
<p>Find me in app/views/likes/toggle.html.erb</p>

app/views/likes/toggle.js.erb
console.log('like toggle called');


var newLike = $('<%= escape_javascript render "posts/post_like_link", post: @post %>');


// console.log('#post-<%= @post.id %>-likes');
// $('#post-<%= @post.id %>-likes').empty();
$('#post-<%= @post.id %>-likes').html(newLike);

new Noty({
    text: 'Like Status Changed!',
    theme: 'relax',
    type: 'success',
    layout: 'topRight'
}).show();

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
	<div>

		<p><%= post.content %></p>
		<p><%= post.user.email %></p>
		<% if user_signed_in? && post.user_id ==  current_user.id %>
		<p><%= link_to "Delete", destroy_post_path(post.id), method: :delete, remote: true %></p>
		<% end %>

		<% if user_signed_in? %>
		<p>
			<sub id="post-<%= post.id %>-likes" class="post-like-status">
				<%= render 'post_like_link', post: post %>
			</sub>
		</p>
		<% else %>
		<sub>
				<%= post.likes.length %> Likes
		
			</sub>

		<% end %>

		<div>
			<%= render 'comments/post_comment', post: post %>
		</div>
		
	</div>
</li>

app/views/posts/_post_like_link.html.erb
<span>

	<%= post.likes.length %>

	<%= link_to post.like_status_string(current_user.id), toggle_like_path(post.id), method: :post, remote: true %>

</span>

app/views/posts/create.js.erb
console.log("new post created");


var newPost = $('<%= escape_javascript render "post", post: @post %>');

$('#posts-list').prepend(newPost);

new Noty({
    text: 'Someone just posted!',
    theme: 'relax',
    type: 'warning',
    layout: 'topRight',
    timeout: 1000,
}).show();

app/views/posts/destroy.js.erb
console.log('destroy post called');

$('#post-<%= @post_id %>').remove();

new Noty({
    text: 'Post Deleted',
    theme: 'relax',
    type: 'warning',
    layout: 'topRight'
}).show();

app/views/posts/home.html.erb
<main id="posts-home">

	<div>Group Links</div>

	<div class="deewar-posts">
		<div class="new-post-form">
			<% if user_signed_in? %>
			<%= form_for @post, remote: true do |f| %>
				<%= f.label :content %>
				<%= f.text_area :content %>

				<%= f.submit %>
			<% end %>
			<% end %>
		</div>

		<div >
			<ul id="posts-list" class="posts-list">
				<% @posts.reverse.each do |p| %>
				<!--  -->
					<%= render 'post', post: p %>
				<% end %>
			</ul>


		</div>
		

	</div>


	<div>Friends</div>

</main>

app/views/users/profile_page.html.erb
<h1>Profile Page</h1>


<p><%= @user.email %></p>

<img src="<%= @user.avatar %>">

<%= form_for @user, url: user_avatar_upload_path(@user.id), html: { multipart: true }, method: :post do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit %>
<% end %>